Drop Java 8
playframework/anorm pull request #488
Opened 2022-09-29 13:38 UTC by mkurz

2022-09-29 15:24 UTC, cchantep requested changes
I'm not really ok with that. There are still project using Java8, and that doesn't have a notable cost for Anorm.

2022-09-29 15:33 UTC, mkurz commented
Hmm.. We decided to drop Java 8 for Play, see https://github.com/playframework/playframework/issues/11078. The problem is more and more libraries Play depends on are not getting published anymore for Java 8, see https://github.com/playframework/playframework/issues?q=author%3Ascala-steward+label%3Atopic%3Ajdk-next+is%3Aclosed+
Also slick just dropped support for Java 8: https://github.com/slick/slick/pull/2557

I guess, as soon as we publish Play with artifacts that are build with bytecode for Java 11+ you will have a problem with anorm (?) since you depend on Play libraries.
We can wait to merge this here, but in the end I think there will not really be a choice.
I know some project still use Java 8, but there are not public releases anymore and more projects dropping it already...

2022-09-29 16:11 UTC, ihostage commented
**Anorm 2.6.x** and **2.7.x** still support Java 8, right?
If yes, I think it's a good compromise with the ability to move forward 🚀

2022-09-29 16:13 UTC, mkurz commented
> Anorm 2.6.x and 2.7.x still support Java 8, right?

Yes, I am now just working against the main branch. So there could still be new 2.7.x releases with support for Java 8 (and Scala 2.11)

2022-09-29 16:39 UTC, mkurz commented on project/Common.scala
> +        Seq("-release", "11")
To be honest I would even drop Scala 2.12... build.sbt does lot of conditional stuff to make everyhing work. I think it's time to move on for people. Scala 2.13 has been out for a long time already and it just gets harder and harder to support older Scala and Java releases...

2022-09-29 16:40 UTC, mkurz commented on build.sbt
> +      "com.google.inject" % "guice" % "5.1.0" % Test, // TODO: Remove when depending on play-jdbc/-specs2 2.8.x+
`playVer` is 2.6.14.... So need to pull in newer Guice version that works with Java 17... It's only in test scope however. But I think this needs more refactoring...

2022-09-29 16:47 UTC, mkurz commented on project/Common.scala
> +        Seq("-release", "11")
BTW: I do not se a reason to not set `release` for Scala 3, should be totally fine.

2022-09-29 16:48 UTC, mkurz commented
At least the pr is green now. I will convert it to a draft pull request. We can wait to merge it at the very end, after Play has a release with Java 11+ only support.

2022-09-29 22:26 UTC, cchantep commented
> Hmm.. We decided to drop Java 8 for Play, see [playframework/playframework#11078](https://github.com/playframework/playframework/issues/11078). The problem is more and more libraries Play depends on are not getting published anymore for Java 8, see https://github.com/playframework/playframework/issues?q=author%3Ascala-steward+label%3Atopic%3Ajdk-next+is%3Aclosed+ Also slick just dropped support for Java 8: [slick/slick#2557](https://github.com/slick/slick/pull/2557)
> 
> I guess, as soon as we publish Play with artifacts that are build with bytecode for Java 11+ you will have a problem with anorm (?) since you depend on Play libraries. We can wait to merge this here, but in the end I think there will not really be a choice. I know some projects still use Java 8, but there are no public releases anymore and more projects dropping it already...

I'm strongly against that choice.
I would rather cut the dependencies (not many) that would be broken.

2022-09-30 09:11 UTC, ihostage commented
@cchantep Cedric, are you against with drop support Java 8 for Play or for Anorm?

2022-09-30 09:13 UTC, mkurz commented
The problem is a lot of people support dropping Java 8 in Play, see https://github.com/playframework/playframework/issues/11078

> I would rather cut the dependencies (not many) that would be broken.

This is not possbile, some essential libraries do not publish Java 8 anymore. This is also becoming a security problem if we can not upgrade libraries anymore....
I think we have to realize that it's time to move on... We can not support Java 8 forever.

@cchantep Do you run applications on Java 8? Is it a problem to move to at least Java 11?

2022-09-30 09:26 UTC, ihostage commented
> This is not possbile, some essential libraries do not publish Java 8 anymore. This is also becoming a security problem if we can not upgrade libraries anymore....

Matthias, it's not only with security updates. We needs a new versions of libraries (like Guice) for support a new version of Java (for example 17). And if we want that Play might be work with a new Java versions we must drop support old versions 🤷‍♂️ We can't sit on two chairs at the same time 🤷‍♂️ 
But of course, Play 2.8 and Anorm 2.6/2.7 can run on Java 8 as now.

2022-09-30 11:36 UTC, cchantep commented
@ihostage @mkurz Thanks for the feedbacks.

> are you against with drop support Java 8 for Play or for Anorm?

I would say both. But much more against for the standalone library like Anorm, Play-JSON and Play-WS, where on one side a compatibility is lost and on this otherwise currently the compatibility is already there with quite no cost.

> Do you run applications on Java 8? Is it a problem to move to at least Java 11?

I'm not the only one. I cannot always (unfortunately) chose the JVM version.

> We can not support Java 8 forever

As long as enterprise are still deploying Java 8 (and against there is quite no cost to maintain the compatiblity).

If some really one some artifact specifically built for late JVM, then rather add a cross build with a specific artifact name.

With all the community drama the past years, and the drastic impact on Play projects, dropping compatibility really doesn't seem going in the right way for me.

2022-09-30 14:46 UTC, mkurz commented
It's not always so easy. If we want to support newer Java versions, we probably just have to drop older ones.
For example have a look at https://github.com/playframework/play-doc/pull/155: It is upgrading parboiled to support Java 17. Now, the problem is, only the latest release supports Java 16+, but at the same time dropped support for Java 8, please see: https://github.com/sirthias/parboiled/pull/195 So what should we do now? Such things are happen more and more...
A lot of people asking when will Play finally support Java 17, but basically no one was against dropping Java 8. We announced that along time ago: https://twitter.com/playframework/status/1513823030904082440 (no negative reactions). Also on https://github.com/playframework/playframework/issues/11078 just positive reactions.
Also, we are "just" setting the baseline to Java 11 now. Spring 6 will be much more aggressive and will require Java 17: https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6
And given Spring is the king in the Java world, I think it should be acceptable to finally drop Java 8 in Play.
Actually you are the first one that is really against that change.

2022-09-30 14:47 UTC, mkurz commented
Plus: You can still keep using Play 2.8.x, we will support it for a while (probably like 6-12 month when Play 2.9 is released. That should give people even more time to upgrade. Java 8 was released 8 years ago now, and probably it will be 9 when we stop support Java 8 in 2.8.x. Java 8 does not even has public updates anymore (do you pay for security fixes?

2022-10-05 18:06 UTC, cchantep commented
> It's not always so easy. If we want to support newer Java versions, we probably just have to drop older ones.

We didn't have such issue previously.

> For example have a look at [playframework/play-doc#155](https://github.com/playframework/play-doc/pull/155): It is upgrading parboiled to support Java 17.

That's why I would prefer to break this dependency, or as it's only tooling run only doc job in such JVM.

> Also on [playframework/playframework#11078](https://github.com/playframework/playframework/issues/11078) just positive reactions.

That's not comparable.
Playframework is a framework, so already comes with constraints and such update could not be such a big step there.
But in project rather using standalone lib such as anorm or play-json (or play-ws), it's also because more flexibility is required.

> Also, we are "just" setting the baseline to Java 11 now. Spring 6 will be much more aggressive and will require Java 17: https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6 And given Spring is the king in the Java world, I think it should be acceptable to finally drop Java 8 in Play. Actually you are the first one that is really against that change.

If the goal is to do another Spring, I'm sorry but then ...

2022-10-05 19:10 UTC, ihostage commented
@cchantep Cédric, how do you propose to drop support Java 8 for Play (we already know that we can't don't do that, because we must support Java 17), but still support Java 8 for Anorm? 🤔 
If you have a clear plan how to do this, please share it 🙏

2022-10-06 07:35 UTC, cchantep commented
Either drop play-doc integration, or run it in a separate CI job.

2023-04-26 19:43 UTC, gaeljw commented
Not sure what's the status about this but definitely agree that we should move on. Many major libraries and frameworks stopped supporting Java 8 (Mockito recently on top of my head). It's also our responsibility as maintainers to incentivize others to move on.

2023-04-27 11:53 UTC, cchantep commented
> It's also our responsibility as maintainers to incentivize others to move on.

No it's not.
Anorm is a standalone library. Not a framework.
It should be as less intrusive as it can, considering the cost.
And there the cost of maintaining compatibility considering the advantage is not in favor of dropping the support.

2025-07-06 06:31 UTC, gaeljw commented
[Scala 3.8+ requires Java 17+](https://www.scala-lang.org/news/next-scala-lts-jdk.html). Even though this is for reasons that are mostly not applicable to a library, this is an additional signal that dropping Java 8 is perfectly fine nowadays.

I'd argue that users that want (need?) to stay on Java 8 probably don't upgrade their libraries often. They can stay on the latest minor version that works for them. It's not like the library is not in a stable state where there are bugfixes releases every week.

2026-03-27 10:51 UTC, mkurz commented
+1 Make java 17 new baseline.

2026-03-27 10:52 UTC, mkurz commented
@gaeljw you can just pick up this pull request here and continue the work, thanks!

2026-05-15 12:37 UTC, gaeljw commented
Closing in favour of #708

2026-05-15 12:37 UTC, closed without merging